### ISSUE TITLE
API implementation

### ISSUE THREAD

**Issue by innoflash** [edalzell/laravel-passwordless-login#20]
So from the current setting i see this works only for a web interface but how about we extend it to API logins as well. 

For an API a user might wanna generate a token or do something on success. I am thinking of making a callback in the trait to do extra staff. That might as well fix the issue the last issue was having. Will try implement it later today and you guys evaluate

**Comment by edgrosvenor** [comment]
@innoflash Let me know if you run into any roadblocks with this. I'm going to have a guy at work use this package to integrate with an API starting next week. We'll be using Airlock there. So he can probably jump in and give you a hand with that integration if needed.

**Comment by edgrosvenor** [comment]
@innoflash I pulled in what you've done so far because I'm desperately trying to figure out why I can't get this package to work for me now. The user gets logged in with no trouble, but immediately upon redirecting, the user is no longer logged in. Which is really weird because I specifically test for this in my tests and they pass.

Have you had any issues using this in an actual Laravel app?

**Comment by edgrosvenor** [comment]
@innoflash Never mind the crisis I was having. I think I uncovered a bug, or at least a very undesirable behavior, in the Laravel test suite. It seems to just assume certain middleware is there whether it is or not. I had forgotten or at some point one of us had accidentally removed the web middleware from the login route. So people were getting logged in and then immediately logged out because the session was never actually created. But in the tests the user was persisting after the redirect so it looked like everything was fine. 

Anyway, we're all good to keep pushing toward api integration.

**Comment by innoflash** [comment]
You did an amazing discovery. Honestly i was failing to get why we couldn't get the logged in user after redirection. Thumbs up buddy

**Comment by salvationarinze** [comment]
I use sanctum and fetching user after redirection returns null
