### ISSUE TITLE
Does not work with StudlyCase namespaces

### ISSUE THREAD

**Issue by leepownall** [edalzell/laravel-passwordless-login#39]
Hello, thanks for a great package!

I'm trying to use this package where the User model namespace is StudlyCase`HelloWorld\Models\User`.

The url that is generated looks like:

```
/magic-login/26
    ?expires=1591106096
    &user_type=helloworld-models-user
    &signature=3e62a0eb8d189584d11850...
```

The trouble is `getUserClass` returns `Helloworld\Models\User` with a lower case 'w' which means `$userModel::findOrFail(request('uid'))` fails as the namespace isn't correct.

The README mentions setting `LPL_USER_MODEL` but I don't believe that is being used anywhere apart from in the tests?

**Comment by edgrosvenor** [comment]
@leepownall Good catch.  When I first wrote the package I was thinking it was just going to be used for a single authenticatable model per site. But we pretty quickly set it up to work with more than one, so the configured model became mostly useless. I could reincorporate it but I think maybe it makes more sense to move it out of the docs and just fix this issue the right way.

I think this should just be a simple matter of reworking this method a little bit: https://github.com/grosv/laravel-passwordless-login/blob/master/src/PasswordlessLoginService.php#L52

I think if we split at the \ instead of replacing it with - and then Str::snake() on each of the array parts before joining them with - and change Str::title to Str::studly here https://github.com/grosv/laravel-passwordless-login/blob/master/src/PasswordlessLoginService.php#L42 it should work.

I should hopefully have time this weekend to do this. If you think you're up for submitting a PR in the mean time, that would be fantastic. Otherwise watch this space for a fix.
