### ISSUE TITLE
Redirect Url doesn't work

### ISSUE THREAD

**Issue by argia-andreas** [edalzell/laravel-passwordless-login#42]
Hi!
Thanks for a great package!

I cant get the custom redirect url to work.
This is the code im using:
```php
$generator = new LoginUrl($user);
$generator->setRedirectUrl('/app/' . $deviceName); //device name is a string
$url = $generator->generate();
```

The link i get is similar to this:
`https://domain.name/magic-login/1?expires=1598101993&redirect_to=%2Fapp%2Fdevicenamehere&user_type=app-user&signature=signature`

But it always redirects to the root. ie. /
If I change the default redirect to /example.
It always redirects to /example.. but never to the custom redirect url.

Any idea what the problem could be?

Thank you!

**Comment by argia-andreas** [comment]
Ok, nevermind. :-)

I found the issue.
I was also using the trait on the user model and had this in User.php:
```php
public function getRedirectUrlAttribute(): string
{
    return config('laravel-passwordless-login.redirect_on_success');
}
```

Works perfect now once i removed it :-)

**Comment by afzafri** [comment]
I'm facing the same issue. I have removed the trait from my User model, but the custom redirect url still not working

**Comment by dajoeberlei** [comment]
+1 having the same issue. Don't know how to fix it :-(

The link shows the redirect_url like described above:
``https://domain.name/magic-login/1?expires=1598101993&redirect_to=%2Fapp%2Fdevicenamehere&user_type=app-user&signature=signature``

I also have removed the trait from the user since im also only using the standard user model to use the passwordless login but still i get redirected to the root page.
